### ISSUE TITLE
handle missing USER env var

### ISSUE THREAD

**Issue by andreineculau** [Linuxbrew/install#48]
I'm trying out circleci, and I've noticed that their images don't have a USER env var, thus linuxbrew installation fails.
Easy workaround `export USER=$(whoami)` but would be nicer if linuxbrew would handle this itself.

**Comment by sjackman** [comment]
Thanks for the bug report, Andrei. Would you like to open a pull request to fix this issue?

For CircleCI, I recommend using the `linuxbrew/brew` Docker image.
See for example https://github.com/brewsci/homebrew-bio/blob/07cdffa0c403ec4d4105bbbbf7a697af90cc6e4b/.circleci/config.yml#L4-L5

```yaml
version: 2
jobs:
  build-linux:
    docker:
      - image: linuxbrew/brew
```
